{"ast":null,"code":"export default async function get() {\n  const url = \"https://cubioinfo.com/aptitude-test/api/testitems/1\";\n\n  try {\n    const response = await fetch(url);\n\n    if (response.ok) {\n      return await response.clone().json().catch(() => response.text()); // return await response.json();\n    }\n\n    if (response.status <= 501) {\n      console.log(response.status); // eslint-disable-next-line prefer-promise-reject-errors\n\n      alert(\"error\", response.status);\n    }\n  } catch (error) {\n    if (error.response) {\n      /*\n       * The request was made and the server responded with a\n       * status code that falls out of the range of 2xx\n       */\n      console.log(error.response.data);\n      console.log(error.response.status);\n      console.log(error.response.headers);\n    } else if (error.request) {\n      /*\n       * The request was made but no response was received, `error.request`\n       * is an instance of XMLHttpRequest in the browser and an instance\n       * of http.ClientRequest in Node.js\n       */\n      console.log(error.request);\n    } else {\n      // Something happened in setting up the request and triggered an Error\n      console.log(\"Error\", error.message);\n    }\n\n    console.log(error.config);\n  }\n}","map":{"version":3,"sources":["/Users/apple/Documents/GitHub/OCSCE/src/service/get.js"],"names":["get","url","response","fetch","ok","clone","json","catch","text","status","console","log","alert","error","data","headers","request","message","config"],"mappings":"AAAA,eAAe,eAAeA,GAAf,GAAqB;AAClC,QAAMC,GAAG,GAAG,qDAAZ;;AACA,MAAI;AACF,UAAMC,QAAQ,GAAG,MAAMC,KAAK,CAACF,GAAD,CAA5B;;AACA,QAAIC,QAAQ,CAACE,EAAb,EAAiB;AACf,aAAO,MAAMF,QAAQ,CAClBG,KADU,GAEVC,IAFU,GAGVC,KAHU,CAGJ,MAAML,QAAQ,CAACM,IAAT,EAHF,CAAb,CADe,CAKf;AACD;;AACD,QAAIN,QAAQ,CAACO,MAAT,IAAmB,GAAvB,EAA4B;AAC1BC,MAAAA,OAAO,CAACC,GAAR,CAAYT,QAAQ,CAACO,MAArB,EAD0B,CAE1B;;AACAG,MAAAA,KAAK,CAAC,OAAD,EAAUV,QAAQ,CAACO,MAAnB,CAAL;AACD;AACF,GAdD,CAcE,OAAOI,KAAP,EAAc;AACd,QAAIA,KAAK,CAACX,QAAV,EAAoB;AAClB;;;;AAIAQ,MAAAA,OAAO,CAACC,GAAR,CAAYE,KAAK,CAACX,QAAN,CAAeY,IAA3B;AACAJ,MAAAA,OAAO,CAACC,GAAR,CAAYE,KAAK,CAACX,QAAN,CAAeO,MAA3B;AACAC,MAAAA,OAAO,CAACC,GAAR,CAAYE,KAAK,CAACX,QAAN,CAAea,OAA3B;AACD,KARD,MAQO,IAAIF,KAAK,CAACG,OAAV,EAAmB;AACxB;;;;;AAKAN,MAAAA,OAAO,CAACC,GAAR,CAAYE,KAAK,CAACG,OAAlB;AACD,KAPM,MAOA;AACL;AACAN,MAAAA,OAAO,CAACC,GAAR,CAAY,OAAZ,EAAqBE,KAAK,CAACI,OAA3B;AACD;;AACDP,IAAAA,OAAO,CAACC,GAAR,CAAYE,KAAK,CAACK,MAAlB;AACD;AACF","sourcesContent":["export default async function get() {\n  const url = \"https://cubioinfo.com/aptitude-test/api/testitems/1\";\n  try {\n    const response = await fetch(url);\n    if (response.ok) {\n      return await response\n        .clone()\n        .json()\n        .catch(() => response.text());\n      // return await response.json();\n    }\n    if (response.status <= 501) {\n      console.log(response.status);\n      // eslint-disable-next-line prefer-promise-reject-errors\n      alert(\"error\", response.status);\n    }\n  } catch (error) {\n    if (error.response) {\n      /*\n       * The request was made and the server responded with a\n       * status code that falls out of the range of 2xx\n       */\n      console.log(error.response.data);\n      console.log(error.response.status);\n      console.log(error.response.headers);\n    } else if (error.request) {\n      /*\n       * The request was made but no response was received, `error.request`\n       * is an instance of XMLHttpRequest in the browser and an instance\n       * of http.ClientRequest in Node.js\n       */\n      console.log(error.request);\n    } else {\n      // Something happened in setting up the request and triggered an Error\n      console.log(\"Error\", error.message);\n    }\n    console.log(error.config);\n  }\n}\n"]},"metadata":{},"sourceType":"module"}